### ISSUE TITLE
Error When Running Webpack Dev Server

### ISSUE THREAD

**Issue by Ixonal** [typescript-nameof/nameof#11]
I integrated the package into my Webpack project as instructed, and it builds fine normally, but when I try to run the webpack dev server with it, I get a weird error:

```
[webpack-dev-middleware] HookWebpackError: {path omitted}/node_modules/webpack-dev-server/client/modules/logger/index.js:671:12: [nameof]: Unable to find a returned expression in the specified function.
{stack trace omitted}
caused by plugins in Compilation.hooks.processAssets
```

Is there something special that needs to be done to enable running this on the dev server?

**Comment by manuth** [comment]
Hello - Thank you so much for your interest in this project 😄 

This indeed sounds strange.
The error actually indicates an incorrect use of the lambda-form of `nameof()` (i.e. (`nameof<MyType>(() => my.property.path))`).

Could you please provide a repository for reproducing the error?

**Comment by Ixonal** [comment]
I'll look into getting something to reproduce this set up. For now, I'm not using the lambda form, just the basic form against a class name. Something along the lines of (ignoring imports)...

```typescript

@inject(scopedOf(RequestService), nameof(FooService))
export class FooService {
  constructor(private _requestService: RequestService) {}
}

```

The issue seems to occur even if I don't use nameof anywhere in my code, though. It seems to be tied to the use of getCustomTransformers in the webpack config file.

**Comment by Ixonal** [comment]
Alright, this repo replicated the issue for me https://github.com/Ixonal/NameofErrorTestCase

**Comment by manuth** [comment]
I'm terribly sorry for the inconvenience.
Looks like the issue lies burried down deeper than I would have expected.

To fix this, I have some refactoring to do.

I'll let you know once I managed it to get it fixed

**Comment by Ixonal** [comment]
Don't rush yourself. I'm just using magic strings right now, so it'll work until this gets fixed.

**Comment by manuth** [comment]
Just giving you a little update - I could pin down the issue now.
The error is caused by `nameof` not being able to handle the `!function() { }()` expressions which are generated by webpack.

I have to give it a little more thoughts on how to (slightly) restructure `typescript-nameof`.

**Comment by manuth** [comment]
Alright! I managed it to fix it
The fix will be part of the next version.

Thank you so much for reporting

**Comment by Ixonal** [comment]
thanks for the quick response on this! Any idea when that version will be released?

**Comment by manuth** [comment]
I'm trying to get it released tonight - not making promises, though

**Comment by Ixonal** [comment]
Alright, I'll try it out when I get to work on Monday

**Comment by manuth** [comment]
Managed it to get it published now 😄
Please let me know whether or not it's working out for you

**Comment by manuth** [comment]
Alright - that was quite a ruckus
Just noticed that all my access tokens were outdated

But it's fixed now and the new version was published.

Please let me know whether or not it works out well for you 😄

**Comment by Ixonal** [comment]
Just started the app in dev server and didn't get any errors this time! Also went ahead and looked in the generated source and it correctly transformed to the correct string, so this looks to be resolved. Thanks again for the quick response on this.

**Comment by manuth** [comment]
Awesome!
You're most welcome
Thanks for your interest in this project 😄
