### ISSUE TITLE
Consider using `unknown` instead of `any` type

### ISSUE THREAD

**Issue by ignas-sedunovas** [typescript-nameof/nameof#12]
Hi, it seems that the recommended eslint rule [@typescript-eslint/no-unsafe-call](https://typescript-eslint.io/rules/no-unsafe-call/) complains about the `any` type usage.

Could you consider using `unknown` instead of `any` inside [INameOfProvider.cts](https://github.com/typescript-nameof/nameof/blob/main/packages/common-types/src/INameOfProvider.cts)?

**Comment by manuth** [comment]
Thanks for your feedback!
I updated the code to apply to the `@typescript-eslint/no-unsafe-call` now.

It might take a moment for me to publish a new version since I'm trying to migrate over to GitHub Actions.

**Comment by neurolag** [comment]
Loll looks like v0.0.11 has already been published a year ago automatically.
Its just the GitHub release that hasn't been created for whatever reason
