### ISSUE TITLE
Does it support Enums?

### ISSUE THREAD

**Issue by fairking** [typescript-nameof/nameof#5]
As far as I can see it is not:
``` ts
export enum MyEnum {
  Name1,
  Name2
}

console.log(nameof(MyEnum.Name1)) // compile error TS2769 (TS) No overload matches this call.
```

Or maybe the syntax is different.

**Comment by manuth** [comment]
Thanks for your interest in this project! 😄 

Enums are supported - even `const enum`s.
I cannot reproduce your error.

Do you have a copy of the nun-functioning project somewhere available?
