### ISSUE TITLE
Naming complaints with `babel` plugin

### ISSUE THREAD

**Issue by philsherry** [typescript-nameof/nameof#8]
If I add the recommended code in my `babel.config.js`:
```json
{
  plugins: [
    "@typescript-nameof/babel"
  ]
}
```
I get this:
```log
Parsing error: Cannot find module '@typescript-nameof/babel-plugin-babel'
…
If you want to resolve "@typescript-nameof/babel", use "module:@typescript-nameof/babel"
```

If I make the suggested change my code works, but I'm wondering whether this is something that is better addressed in the plugin and the docs?

**Comment by manuth** [comment]
Thank you very much for pointing this out!
I will have this changed in the docs asap

Thanks for your interest in this project

**Comment by manuth** [comment]
I have updated the documentation properly now.
Test cases have been added for making sure that running the babel compiler using the package name (prefixed with `module:`) properly.

Thank you very much for reporting 😄
