### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by BonnieSoftware** [typescript-nameof/nameof#9]
If this project is abandoned I will look to fork it, I know... yet another fork... but there is a good PR left hanging and a bug report that is quite an issue, @manuth are you still maintaining this project and if not are you willing to transfer ownership of it?

**Comment by manuth** [comment]
I plan to still maintain this
However, student's life is quite rough on me atm so I'd love to add collaborators to this project if anyone feels like it.
